[tasks.plan]
description = "Build and preview diff"
run = """
if [[ $(uname) == "Darwin" ]]; then
  darwin-rebuild build --flake .#
else
  nixos-rebuild build --flake .#
fi
nix store diff-closures /run/current-system ./result
"""

[tasks.apply]
description = "Apply configuration"
run = """
if [[ $(uname) == "Darwin" ]]; then
  sudo darwin-rebuild switch --flake .#
else
  sudo nixos-rebuild switch --flake .#
fi
"""

[tasks.update]
description = "Update flake inputs"
run = "nix flake update && git add flake.lock"

[tasks.fmt]
description = "Format nix files"
run = "nix fmt ."

[tasks.check]
description = "Run flake checks"
run = "nix flake check --all-systems"

[tasks.gc]
description = "Garbage collect nix store"
run = "nix-collect-garbage -d"
